#!/bin/sh

set -xe

TARGET_HOSTNAME="retroroot"
TARGET_TIMEZONE="Europe/Paris"
ROOT_PASS=retroroot

# setup certificates
#apk add ca-certificates
update-ca-certificates

# install apline setup scripts
apk add alpine-conf

# update root password
echo "root:$ROOT_PASS" | chpasswd

# set hostname
setup-hostname $TARGET_HOSTNAME
echo "127.0.0.1    $TARGET_HOSTNAME $TARGET_HOSTNAME.localdomain" > /etc/hosts

# setup keymap
#apk add kbd-bkeymaps
#rc-update add loadkmap
setup-keymap fr fr
#exit 1234

# time
apk add chrony tzdata
setup-timezone -z $TARGET_TIMEZONE

# other stuff
apk add nano htop curl wget bash bash-doc bash-completion chsh \
  util-linux pciutils usbutils coreutils binutils findutils grep iproute2

# TODO
#sed -i 's/\/bin\/ash/\/bin\/bash/g' /etc/passwd
