#!/bin/sh

set -xe

# include config file
source $(dirname "$0")/settings.cfg

# setup certificates
#apk add ca-certificates
update-ca-certificates

# install apline setup scripts
apk add alpine-conf

# update root password
echo "root:$TARGET_ROOT_PASS" | chpasswd

# set hostname
setup-hostname $TARGET_HOSTNAME
echo "127.0.0.1    $TARGET_HOSTNAME $TARGET_HOSTNAME.localdomain" > /etc/hosts

# setup keymap
setup-keymap fr fr

# time
apk add chrony tzdata
setup-timezone -z $TARGET_TIMEZONE

# misc
apk add nano htop curl wget bash bash-doc bash-completion \
  util-linux pciutils usbutils coreutils binutils findutils \
  file grep iproute2

# hardware accelerated gpu
apk add mesa-dri-vc4

# set bash as default shell
sed -i 's/\/bin\/ash/\/bin\/bash/g' /etc/passwd

