#!/bin/sh

set -xe

# include config file
source $(dirname "$0")/settings.cfg

apk add sudo

for GRP in spi i2c gpio; do
	addgroup --system $GRP
done

for GRP in adm dialout cdrom audio users video games input tty gpio spi i2c netdev; do
  adduser root $GRP
done

