#!/bin/sh

set -xe

# include config file
source $(dirname "$0")/settings.cfg

apk add eudev openssh haveged

for service in devfs dmesg; do
	rc-update add $service sysinit
done

for service in modules sysctl hostname bootmisc swclock syslog swap; do
	rc-update add $service boot
done

# TODO: enable wifi
# wpa_supplicant wpa_cli
for service in dbus haveged sshd chronyd local networking avahi-daemon bluetooth; do
	rc-update add $service default
done

setup-udev -n

for service in mount-ro killprocs savecache; do
	rc-update add $service shutdown
done

# enable ssh as root
echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config

